### ISSUE TITLE
Vimgrepコマンドが利用不可になっている

### ISSUE THREAD

**Issue by ToruIwashita** [fuenor/qfixgrep#4]
以前までは `Vimgrep` 等のコマンドがあり、コマンドラインで grep を実行可能だったと思いますが、最近使ってコマンドがなくなっている事に気づきました。

コマンド定義が軒並みコメントアウトされていたので、意図的に利用できないようにしたのだろうと思っていますが、以前のように利用できるようにして頂く事はできないでしょうか。

https://github.com/fuenor/qfixgrep/blob/5f8b14fa2af0c6010c64dd0e0004c8502e515f68/autoload/qfixgrep.vim#L298-L318

**Comment by fuenor** [comment]
> コマンド定義が軒並みコメントアウトされていたので、意図的に利用できないようにしたのだろうと思っていますが、以前のように利用できるようにして頂く事はできないでしょうか。

これは同じようなコマンドが大量に登録されてしまい、使い勝手が悪いということでコメントアウトしたものです。
今回のご要望に対応して`.vimrc`に以下を追加すると、全てのコマンドが追加されるようにしました。
```vim
let g:MyGrep_Commands = 1
```

また、一部のコマンドのみ有効にしたい場合は、以下のように任意のコマンドのみを`.vimrc`でユーザが追加可能にしました。

```vim
command! -nargs=* -bang Vimgrep     call qfixgrep#QFixCmdGrep('Vimgrep', <q-args>)
```
各コマンドの個別の定義については以下を参照してください。
https://github.com/fuenor/qfixgrep/blob/d787fcbdbe17280356dc26b2c60ea3e11cac6b33/plugin/mygrep.vim#L20-L40

ご存知とは思いますが`vimgrep`に関してはQFixGrepを経由せずコマンドラインから実行しても、プレビューを始めとする各種機能は使用可能です。
```vim
:vimgrep foobar * |cope
```
特に問題なければこの仕様でfixしようと考えています。ありがとうございます。

**Comment by ToruIwashita** [comment]
オプションでのコマンドON/OFFと、個別に設定できる実装はすごく使い勝手が良く、大変助かります。

ご対応ありがとうございました:bow:

**Comment by ToruIwashita** [comment]
```
:vimgrep foobar * |cope
```

こちらもありがとうございます。（こちらを使うことも考えてはいましたが、やはり `Vimgrep` の方が使いやすいので issue を立てさせてもらっていました。
